// You can import and use all API from the 'vscode' module
// as well as import your extension to test it
import * as assert from 'assert';
import { beforeEach } from 'mocha';
import * as path from 'path';
import * as vscode from 'vscode';
import { repoPath } from '../../../utils/config';
import { Filter, getItems, getMarkdown, inNoteRepo } from '../../../utils/item';
import { resetFixture, stringArrayStrictEqual, toRepoPath } from '../lib';

suite('utils/item Test Suite', () => {
    vscode.window.showInformationMessage('Start item tests.');

    beforeEach(() => {
        resetFixture();
    });

    test('getItems() test', async () => {
        let expected = toRepoPath([
            ".",
            "./yes.md",
            "./no.md",
            "./notfile.md",
            "./notfile.md/no.md",
            "./notfile.md/yes.md",
            "./nested",
            "./nested/category",
            "./nested/category/no.md",
            "./nested/category/yes.md",
            "./not-md.txt",
        ]).sort();

        let itemsPath = (await getItems([new Filter(item => true)])).map(item => item.path).sort();
        stringArrayStrictEqual(itemsPath, expected);
    });

    test('inNoteRepo() test', () => {
        assert.ok(inNoteRepo(path.join(repoPath(), "yes.md")));
        assert.ok(inNoteRepo(path.join(repoPath(), "anything/under/it")));
        assert.ok(!inNoteRepo("/not/in/repo"));
    });

    test('getMarkdown() test', async () => {
        // Generated by:
        // find note/dir/ -name "*.md" -type f
        let expected = toRepoPath([
            "./yes.md",
            "./no.md",
            "./notfile.md/no.md",
            "./notfile.md/yes.md",
            "./nested/category/no.md",
            "./nested/category/yes.md",
        ]).sort();

        let itemsPath = (await getMarkdown()).map(item => item.path).sort();
        stringArrayStrictEqual(itemsPath, expected);
    });
});
